name: Releases

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
    - name: Create release notes
      uses: johnyherangi/create-release-notes@main
      id: create-release-notes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        generateReleaseNotes: true
        body: ${{ steps.create-release-notes.outputs.release-notes }}

